In [1]:
import numpy as np
np.random.seed(1337)

In [2]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras import optimizers
from keras.utils import np_utils

Using TensorFlow backend.


In [3]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [4]:
batch_size = 10
nb_classes = 1
nb_epoch = 70000

In [5]:
datapath = "/Train_TEC_mar17.csv"

In [7]:
 def NeuralNetwork(x_train, y_train, x_test, y_test):
        pca = PCA(n_components=7)
        pca.fit(X_train)
        X_train = pca.transform(X_train)
        pca.fit(X_test)
        X_test = pca.transform(X_test)
        X_train = X_train/180000000.0
        X_test = X_test/180000000.0


        model = Sequential()
        model.add(Dense(15, input_shape=(7,)))
        model.add(Activation('tanh'))

        model.add(Dense(11))
        model.add(Activation('tanh'))

        model.add(Dense(1))

        model.summary()
        sgd = optimizers.SGD(lr=0.1,momentum=0.2)
        model.compile(loss='mean_absolute_error', optimizer=sgd, metrics=['accuracy'])

        history = model.fit(X_train, Y_train,
                            batch_size=batch_size, epochs=nb_epoch,
                            verbose=1, validation_data=(X_test, Y_test))


        score = model.evaluate(X_test, Y_test, verbose=0)
        error = score[0]

        plt.plot(history.history['loss'])
        plt.show()
        plt.gcf().clear()

        return error

In [21]:
def main():
    errorLlist = []
    for i in range(0,4):
        data = np.genfromtxt("Train_TEC_mar17.csv",delimiter=',',skip_header=0,dtype=float)
#         data = np.genfromtxt(dataPath+"inputnn" + str(i+1) + ".csv",delimiter=',',skip_header=0,dtype=float)
        X_train = data[:,:4]
        Y_train = data[:,4]
        data = np.genfromtxt("Test_TEC_mar17.csv",delimiter=',',skip_header=0,dtype=float)
#         data = np.genfromtxt(dataPath+"inputnn" + str(i+1) + "_test.csv",delimiter=',',skip_header=0,dtype=float)
        X_test = data[:,:4]
        Y_test = data[:,4]
#         #train and test nueral network for this segment
#         error = NeuralNetwork(X_train,Y_train,X_test,Y_test)
#         errorList.append(error)
        print(X_train)

if __name__ == "__main__":
    main()

[[           nan            nan            nan            nan]
 [1.00000000e+00 3.00000000e+00 2.01700000e+03 1.63888890e-02]
 [1.00000000e+00 3.00000000e+00 2.01700000e+03 4.97222220e-02]
 ...
 [2.00000000e+01 3.00000000e+00 2.01700000e+03 2.39163889e+01]
 [2.00000000e+01 3.00000000e+00 2.01700000e+03 2.39497222e+01]
 [2.00000000e+01 3.00000000e+00 2.01700000e+03 2.39830556e+01]]
[[           nan            nan            nan            nan]
 [1.00000000e+00 3.00000000e+00 2.01700000e+03 1.63888890e-02]
 [1.00000000e+00 3.00000000e+00 2.01700000e+03 4.97222220e-02]
 ...
 [2.00000000e+01 3.00000000e+00 2.01700000e+03 2.39163889e+01]
 [2.00000000e+01 3.00000000e+00 2.01700000e+03 2.39497222e+01]
 [2.00000000e+01 3.00000000e+00 2.01700000e+03 2.39830556e+01]]
[[           nan            nan            nan            nan]
 [1.00000000e+00 3.00000000e+00 2.01700000e+03 1.63888890e-02]
 [1.00000000e+00 3.00000000e+00 2.01700000e+03 4.97222220e-02]
 ...
 [2.00000000e+01 3.00000000e+00 2.0170